# Generated by Django 5.2.7 on 2025-10-13 07:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
