# Generated by Django 5.2.7 on 2025-10-14 17:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_options_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='employee.department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
