# Generated by Django 5.2.7 on 2025-10-27 06:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('employee', '0004_alter_employee_status'),
        ('users', '0002_alter_user_force_password_change'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_usernam_b6ad46_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$', 'Enter a valid phone number (7-15 digits, optional leading +).')]),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_user_usernam_65d164_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['emp_id'], name='users_user_emp_id_4d4e6d_idx'),
        ),
    ]
