# Generated by Django 5.2.7 on 2025-10-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_department_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_password',
            field=models.CharField(blank=True, help_text='Stores auto-generated temporary password for testing/logging.', max_length=128, null=True),
        ),
    ]
