# Generated by Django 5.2.7 on 2025-10-24 14:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField(help_text='Detailed feedback or comments from the reviewer.')),
                ('remarks', models.TextField(blank=True, help_text='Additional notes or suggestions.', null=True)),
                ('rating', models.PositiveSmallIntegerField(default=0, help_text='Numeric rating (1–10 scale).')),
                ('visibility', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Private', help_text='Defines whether the feedback is public or private in dashboards/reports.', max_length=20)),
                ('feedback_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(blank=True, help_text="Client's name or organization giving the feedback.", max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Client Feedback',
                'verbose_name_plural': 'Client Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='GeneralFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField(help_text='Detailed feedback or comments from the reviewer.')),
                ('remarks', models.TextField(blank=True, help_text='Additional notes or suggestions.', null=True)),
                ('rating', models.PositiveSmallIntegerField(default=0, help_text='Numeric rating (1–10 scale).')),
                ('visibility', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Private', help_text='Defines whether the feedback is public or private in dashboards/reports.', max_length=20)),
                ('feedback_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'General Feedback',
                'verbose_name_plural': 'General Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='ManagerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField(help_text='Detailed feedback or comments from the reviewer.')),
                ('remarks', models.TextField(blank=True, help_text='Additional notes or suggestions.', null=True)),
                ('rating', models.PositiveSmallIntegerField(default=0, help_text='Numeric rating (1–10 scale).')),
                ('visibility', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Private', help_text='Defines whether the feedback is public or private in dashboards/reports.', max_length=20)),
                ('feedback_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager_name', models.CharField(blank=True, help_text="Manager's name (auto-filled or entered manually).", max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Manager Feedback',
                'verbose_name_plural': 'Manager Feedbacks',
            },
        ),
    ]
