# Generated by Django 5.2.7 on 2025-10-21 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_initial'),
        ('feedback', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfeedback',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who submitted this feedback', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientfeedback',
            name='department',
            field=models.ForeignKey(blank=True, help_text="Employee's department", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_feedbacks', to='employee.department'),
        ),
        migrations.AddField(
            model_name='clientfeedback',
            name='employee',
            field=models.ForeignKey(help_text='Employee receiving this feedback', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_feedbacks', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='generalfeedback',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who submitted this feedback', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generalfeedback',
            name='department',
            field=models.ForeignKey(blank=True, help_text="Employee's department", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_feedbacks', to='employee.department'),
        ),
        migrations.AddField(
            model_name='generalfeedback',
            name='employee',
            field=models.ForeignKey(help_text='Employee receiving this feedback', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_feedbacks', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='managerfeedback',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who submitted this feedback', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='managerfeedback',
            name='department',
            field=models.ForeignKey(blank=True, help_text="Employee's department", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_feedbacks', to='employee.department'),
        ),
        migrations.AddField(
            model_name='managerfeedback',
            name='employee',
            field=models.ForeignKey(help_text='Employee receiving this feedback', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_feedbacks', to='employee.employee'),
        ),
    ]
