# Generated by Django 5.2.7 on 2025-10-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfeedback',
            name='source_type',
            field=models.CharField(blank=True, editable=False, help_text='Auto-filled field (Admin / Manager / Client) for analytics grouping.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='generalfeedback',
            name='source_type',
            field=models.CharField(blank=True, editable=False, help_text='Auto-filled field (Admin / Manager / Client) for analytics grouping.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='managerfeedback',
            name='source_type',
            field=models.CharField(blank=True, editable=False, help_text='Auto-filled field (Admin / Manager / Client) for analytics grouping.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientfeedback',
            name='visibility',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Private', help_text='Defines whether feedback is visible in dashboards/reports.', max_length=20),
        ),
        migrations.AlterField(
            model_name='generalfeedback',
            name='visibility',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Private', help_text='Defines whether feedback is visible in dashboards/reports.', max_length=20),
        ),
        migrations.AlterField(
            model_name='managerfeedback',
            name='manager_name',
            field=models.CharField(blank=True, help_text="Manager's name (auto-filled if available).", max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='managerfeedback',
            name='visibility',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Private', help_text='Defines whether feedback is visible in dashboards/reports.', max_length=20),
        ),
    ]
