# Generated by Django 5.2.7 on 2025-10-24 07:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_initial'),
        ('feedback', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfeedback',
            name='client_name',
            field=models.CharField(blank=True, help_text="Client's name or organization giving the feedback.", max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='clientfeedback',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who submitted this feedback.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientfeedback',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department of the employee.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_feedbacks', to='employee.department'),
        ),
        migrations.AlterField(
            model_name='clientfeedback',
            name='employee',
            field=models.ForeignKey(help_text='Employee receiving this feedback.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_feedbacks', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='clientfeedback',
            name='feedback_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='clientfeedback',
            name='feedback_text',
            field=models.TextField(help_text='Detailed feedback or comments from the reviewer.'),
        ),
        migrations.AlterField(
            model_name='clientfeedback',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, help_text='Numeric rating (1–10 scale).'),
        ),
        migrations.AlterField(
            model_name='clientfeedback',
            name='remarks',
            field=models.TextField(blank=True, help_text='Additional notes or suggestions.', null=True),
        ),
        migrations.AlterField(
            model_name='clientfeedback',
            name='visibility',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Private', help_text='Defines whether the feedback is public or private in dashboards/reports.', max_length=20),
        ),
        migrations.AlterField(
            model_name='generalfeedback',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who submitted this feedback.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='generalfeedback',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department of the employee.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_feedbacks', to='employee.department'),
        ),
        migrations.AlterField(
            model_name='generalfeedback',
            name='employee',
            field=models.ForeignKey(help_text='Employee receiving this feedback.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_feedbacks', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='generalfeedback',
            name='feedback_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='generalfeedback',
            name='feedback_text',
            field=models.TextField(help_text='Detailed feedback or comments from the reviewer.'),
        ),
        migrations.AlterField(
            model_name='generalfeedback',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, help_text='Numeric rating (1–10 scale).'),
        ),
        migrations.AlterField(
            model_name='generalfeedback',
            name='remarks',
            field=models.TextField(blank=True, help_text='Additional notes or suggestions.', null=True),
        ),
        migrations.AlterField(
            model_name='generalfeedback',
            name='visibility',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Private', help_text='Defines whether the feedback is public or private in dashboards/reports.', max_length=20),
        ),
        migrations.AlterField(
            model_name='managerfeedback',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who submitted this feedback.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='managerfeedback',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department of the employee.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_feedbacks', to='employee.department'),
        ),
        migrations.AlterField(
            model_name='managerfeedback',
            name='employee',
            field=models.ForeignKey(help_text='Employee receiving this feedback.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_feedbacks', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='managerfeedback',
            name='feedback_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='managerfeedback',
            name='feedback_text',
            field=models.TextField(help_text='Detailed feedback or comments from the reviewer.'),
        ),
        migrations.AlterField(
            model_name='managerfeedback',
            name='manager_name',
            field=models.CharField(blank=True, help_text="Manager's name (auto-filled or entered manually).", max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='managerfeedback',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, help_text='Numeric rating (1–10 scale).'),
        ),
        migrations.AlterField(
            model_name='managerfeedback',
            name='remarks',
            field=models.TextField(blank=True, help_text='Additional notes or suggestions.', null=True),
        ),
        migrations.AlterField(
            model_name='managerfeedback',
            name='visibility',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Private', help_text='Defines whether the feedback is public or private in dashboards/reports.', max_length=20),
        ),
    ]
