# Generated by Django 5.2.7 on 2025-10-28 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_employee_options_and_more'),
        ('feedback', '0003_clientfeedback_source_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientfeedback',
            options={'verbose_name': 'Client Feedback', 'verbose_name_plural': 'Client Feedback'},
        ),
        migrations.AlterModelOptions(
            name='generalfeedback',
            options={'verbose_name': 'General Feedback', 'verbose_name_plural': 'General Feedback'},
        ),
        migrations.AlterModelOptions(
            name='managerfeedback',
            options={'verbose_name': 'Manager Feedback', 'verbose_name_plural': 'Manager Feedback'},
        ),
        migrations.AlterField(
            model_name='clientfeedback',
            name='client_name',
            field=models.CharField(blank=True, help_text="Client's name or organization.", max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='clientfeedback',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who submitted this feedback (Admin / Manager / Client).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientfeedback',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department under which the feedback is recorded.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_feedbacks', to='employee.department'),
        ),
        migrations.AlterField(
            model_name='clientfeedback',
            name='feedback_text',
            field=models.TextField(help_text='Detailed feedback or comments.'),
        ),
        migrations.AlterField(
            model_name='clientfeedback',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, help_text='Numeric rating (scale: 1–10).'),
        ),
        migrations.AlterField(
            model_name='clientfeedback',
            name='remarks',
            field=models.TextField(blank=True, help_text='Additional notes or context.', null=True),
        ),
        migrations.AlterField(
            model_name='clientfeedback',
            name='source_type',
            field=models.CharField(blank=True, editable=False, help_text='Auto-filled (Admin / Manager / Client) for analytics grouping.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientfeedback',
            name='visibility',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Private', help_text='Defines whether feedback is visible in employee dashboards.', max_length=20),
        ),
        migrations.AlterField(
            model_name='generalfeedback',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who submitted this feedback (Admin / Manager / Client).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='generalfeedback',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department under which the feedback is recorded.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_feedbacks', to='employee.department'),
        ),
        migrations.AlterField(
            model_name='generalfeedback',
            name='feedback_text',
            field=models.TextField(help_text='Detailed feedback or comments.'),
        ),
        migrations.AlterField(
            model_name='generalfeedback',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, help_text='Numeric rating (scale: 1–10).'),
        ),
        migrations.AlterField(
            model_name='generalfeedback',
            name='remarks',
            field=models.TextField(blank=True, help_text='Additional notes or context.', null=True),
        ),
        migrations.AlterField(
            model_name='generalfeedback',
            name='source_type',
            field=models.CharField(blank=True, editable=False, help_text='Auto-filled (Admin / Manager / Client) for analytics grouping.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='generalfeedback',
            name='visibility',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Private', help_text='Defines whether feedback is visible in employee dashboards.', max_length=20),
        ),
        migrations.AlterField(
            model_name='managerfeedback',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who submitted this feedback (Admin / Manager / Client).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='managerfeedback',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department under which the feedback is recorded.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_feedbacks', to='employee.department'),
        ),
        migrations.AlterField(
            model_name='managerfeedback',
            name='feedback_text',
            field=models.TextField(help_text='Detailed feedback or comments.'),
        ),
        migrations.AlterField(
            model_name='managerfeedback',
            name='manager_name',
            field=models.CharField(blank=True, help_text='Auto-filled with Manager’s name if available.', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='managerfeedback',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, help_text='Numeric rating (scale: 1–10).'),
        ),
        migrations.AlterField(
            model_name='managerfeedback',
            name='remarks',
            field=models.TextField(blank=True, help_text='Additional notes or context.', null=True),
        ),
        migrations.AlterField(
            model_name='managerfeedback',
            name='source_type',
            field=models.CharField(blank=True, editable=False, help_text='Auto-filled (Admin / Manager / Client) for analytics grouping.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='managerfeedback',
            name='visibility',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Private', help_text='Defines whether feedback is visible in employee dashboards.', max_length=20),
        ),
    ]
