# Generated by Django 5.2.7 on 2025-10-23 17:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Employee', 'Employee')], default='Employee', help_text='Defines whether the employee is an Admin, Manager, or Employee.', max_length=20)),
                ('designation', models.CharField(blank=True, help_text='Job title or position (e.g., Developer, Team Lead).', max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, help_text='Official contact number.', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\+91[6-9]\\d{9}$', 'Contact number must start with +91 and be a valid 10-digit Indian mobile number.')])),
                ('status', models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Resigned', 'Resigned')], default='Active', help_text='Employment status.', max_length=20)),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, help_text='Department where the employee works.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employee.department')),
                ('manager', models.ForeignKey(blank=True, help_text='Manager supervising this employee.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['user__first_name'],
            },
        ),
    ]
