# Generated by Django 5.2.7 on 2025-10-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, help_text='Optional short code for department (e.g., HR01, IT02).', max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Marks whether employee is currently active in system.'),
        ),
    ]
