# Generated by Django 5.2.7 on 2025-10-26 18:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, help_text='Optional short code (e.g., HR01, IT02).', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Employee contact number.', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\+91[6-9]\\d{9}$', 'Enter a valid Indian mobile number with +91 prefix.')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, help_text='Job title or position (e.g., Developer, Analyst).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Marks whether employee is currently active in the system.'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Reporting manager for the employee.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Employee', 'Employee')], default='Employee', help_text="Employee's role (Admin, Manager, Employee).", max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Resigned', 'Resigned')], default='Active', help_text='Current employment status.', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(help_text='Linked user account for authentication and login.', on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
