# Generated by Django 5.2.7 on 2025-10-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_department_code_alter_employee_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Resigned', 'Resigned'), ('Inactive', 'Inactive')], default='Active', help_text='Current employment status.', max_length=20),
        ),
    ]
