# Generated by Django 5.2.7 on 2025-10-28 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, help_text='Employee phone number.', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\+91[6-9]\\d{9}$', 'Enter a valid Indian mobile number with +91 prefix.')]),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, help_text='Short department code (e.g., HR01, ENG02).', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, help_text='Job title (e.g., Developer, Analyst).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
