# Generated by Django 5.2.7 on 2025-10-30 00:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_employee_employee_em_role_edc93a_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag for employee.'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Employee', 'Employee')], default='Employee', max_length=20),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['is_deleted'], name='employee_em_is_dele_4bfa82_idx'),
        ),
    ]
