# Generated by Django 5.2.7 on 2025-10-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_employee_address_line1_employee_city_employee_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address_line2',
            field=models.CharField(blank=True, help_text='Additional address line', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, help_text='Gender of the employee', max_length=10, null=True),
        ),
    ]
