# Generated by Django 5.2.7 on 2025-10-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_employee_address_line2_employee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='project_name',
            field=models.CharField(blank=True, help_text='Project the employee is working on', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='reporting_manager_name',
            field=models.CharField(blank=True, help_text="Reporting manager's name", max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
