# Generated by Django 5.2.7 on 2025-10-13 09:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_department_alter_employee_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(default=django.utils.timezone.now)),
                ('evaluation_period', models.CharField(help_text='e.g. WK:10/Nov/2025 - 16/Nov/2025', max_length=100)),
                ('communication_skills', models.PositiveIntegerField(default=0)),
                ('multitasking', models.PositiveIntegerField(default=0)),
                ('team_skills', models.PositiveIntegerField(default=0)),
                ('technical_skills', models.PositiveIntegerField(default=0)),
                ('job_knowledge', models.PositiveIntegerField(default=0)),
                ('productivity', models.PositiveIntegerField(default=0)),
                ('creativity', models.PositiveIntegerField(default=0)),
                ('work_quality', models.PositiveIntegerField(default=0)),
                ('professionalism', models.PositiveIntegerField(default=0)),
                ('work_consistency', models.PositiveIntegerField(default=0)),
                ('attitude', models.PositiveIntegerField(default=0)),
                ('cooperation', models.PositiveIntegerField(default=0)),
                ('dependability', models.PositiveIntegerField(default=0)),
                ('attendance', models.PositiveIntegerField(default=0)),
                ('punctuality', models.PositiveIntegerField(default=0)),
                ('total_score', models.FloatField(default=0.0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, help_text='Department of the employee', null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.department')),
                ('emp', models.ForeignKey(help_text='Employee being evaluated', on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, help_text='Direct manager conducting the review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Performance Evaluation',
                'verbose_name_plural': 'Performance Evaluations',
                'ordering': ['-review_date'],
            },
        ),
    ]
