# Generated by Django 5.2.7 on 2025-11-02 06:58

import django.core.validators
import django.utils.timezone
import performance.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(default=django.utils.timezone.localdate, help_text='Date when the evaluation was conducted.')),
                ('week_number', models.PositiveSmallIntegerField(default=performance.models.current_week_number, help_text='ISO week number (1-53).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(53)])),
                ('year', models.PositiveSmallIntegerField(default=performance.models.current_year, help_text='Year of the evaluation.', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('evaluation_period', models.CharField(blank=True, default='', help_text="Human-readable period (e.g., 'Week 41 (07 Oct - 13 Oct 2025)').", max_length=120)),
                ('evaluation_type', models.CharField(choices=[('Admin', 'Admin Evaluation'), ('Manager', 'Manager Evaluation'), ('Client', 'Client Feedback'), ('Self', 'Self Assessment')], db_index=True, default='Manager', help_text='Type of evaluation conducted.', max_length=20)),
                ('communication_skills', models.PositiveSmallIntegerField(default=0, help_text='Verbal and written communication effectiveness (0-100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('team_skills', models.PositiveSmallIntegerField(default=0, help_text='Ability to work collaboratively in teams (0-100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cooperation', models.PositiveSmallIntegerField(default=0, help_text='Willingness to cooperate with others (0-100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('attitude', models.PositiveSmallIntegerField(default=0, help_text='Overall work attitude and positivity (0-100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('professionalism', models.PositiveSmallIntegerField(default=0, help_text='Professional conduct and behavior (0-100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('technical_skills', models.PositiveSmallIntegerField(default=0, help_text='Technical competency and expertise (0-100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('job_knowledge', models.PositiveSmallIntegerField(default=0, help_text='Understanding of job responsibilities (0-100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('work_quality', models.PositiveSmallIntegerField(default=0, help_text='Quality and accuracy of work output (0-100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('work_consistency', models.PositiveSmallIntegerField(default=0, help_text='Consistency in maintaining standards (0-100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('productivity', models.PositiveSmallIntegerField(default=0, help_text='Work output and efficiency (0-100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('multitasking', models.PositiveSmallIntegerField(default=0, help_text='Ability to manage multiple tasks (0-100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('creativity', models.PositiveSmallIntegerField(default=0, help_text='Innovation and problem-solving creativity (0-100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('dependability', models.PositiveSmallIntegerField(default=0, help_text='Reliability and trustworthiness (0-100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('attendance', models.PositiveSmallIntegerField(default=0, help_text='Regularity and presence at work (0-100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('punctuality', models.PositiveSmallIntegerField(default=0, help_text='Timeliness and punctuality (0-100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_score', models.PositiveIntegerField(default=0, editable=False, help_text='Sum of all metric scores (max 1500).')),
                ('average_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Average score normalized to 0-100 scale.', max_digits=5)),
                ('performance_rating', models.CharField(blank=True, default='', editable=False, help_text='Performance rating based on average score.', max_length=50)),
                ('rank', models.PositiveSmallIntegerField(blank=True, editable=False, help_text='Rank within department for this week/type.', null=True)),
                ('overall_rank', models.PositiveSmallIntegerField(blank=True, editable=False, help_text='Organization-wide rank for this week/type.', null=True)),
                ('remarks', models.TextField(blank=True, help_text='Additional comments or feedback from evaluator.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_finalized', models.BooleanField(default=False, help_text='Whether the evaluation is finalized (locked from editing).')),
            ],
            options={
                'verbose_name': 'Performance Evaluation',
                'verbose_name_plural': 'Performance Evaluations',
                'ordering': ['-review_date', '-average_score', 'employee__user__emp_id'],
            },
        ),
    ]
