# Generated by Django 5.2.7 on 2025-10-14 13:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0003_alter_employee_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(default=django.utils.timezone.now)),
                ('evaluation_period', models.CharField(blank=True, default='', help_text='E.g., WK:10/Oct/2025 - 16/Oct/2025', max_length=120)),
                ('week_number', models.PositiveSmallIntegerField(default=42)),
                ('year', models.PositiveSmallIntegerField(default=2025)),
                ('evaluation_type', models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Client', 'Client'), ('Self', 'Self')], default='Manager', help_text='Who conducted the evaluation.', max_length=20)),
                ('communication_skills', models.PositiveSmallIntegerField(default=0)),
                ('multitasking', models.PositiveSmallIntegerField(default=0)),
                ('team_skills', models.PositiveSmallIntegerField(default=0)),
                ('technical_skills', models.PositiveSmallIntegerField(default=0)),
                ('job_knowledge', models.PositiveSmallIntegerField(default=0)),
                ('productivity', models.PositiveSmallIntegerField(default=0)),
                ('creativity', models.PositiveSmallIntegerField(default=0)),
                ('work_quality', models.PositiveSmallIntegerField(default=0)),
                ('professionalism', models.PositiveSmallIntegerField(default=0)),
                ('work_consistency', models.PositiveSmallIntegerField(default=0)),
                ('attitude', models.PositiveSmallIntegerField(default=0)),
                ('cooperation', models.PositiveSmallIntegerField(default=0)),
                ('dependability', models.PositiveSmallIntegerField(default=0)),
                ('attendance', models.PositiveSmallIntegerField(default=0)),
                ('punctuality', models.PositiveSmallIntegerField(default=0)),
                ('total_score', models.FloatField(default=0.0, help_text='Sum of all metrics (max 1500).')),
                ('average_score', models.FloatField(default=0.0, help_text='Average score out of 100.')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_performances', to='employee.department')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_evaluations', to='employee.employee')),
                ('evaluator', models.ForeignKey(blank=True, help_text='The Admin/Manager/Client who gave the evaluation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Performance Evaluation',
                'verbose_name_plural': 'Performance Evaluations',
                'ordering': ['-review_date', '-created_at'],
                'unique_together': {('employee', 'week_number', 'year', 'evaluation_type')},
            },
        ),
    ]
