# Generated by Django 5.2.7 on 2025-10-14 17:36

import performance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceevaluation',
            name='week_number',
            field=models.PositiveSmallIntegerField(default=performance.models.current_week_number),
        ),
        migrations.AlterField(
            model_name='performanceevaluation',
            name='year',
            field=models.PositiveSmallIntegerField(default=performance.models.current_year),
        ),
    ]
