# Generated by Django 5.2.7 on 2025-10-13 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_department_alter_employee_options_and_more'),
        ('performance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performanceevaluation',
            options={'ordering': ['-review_date', '-created_at'], 'verbose_name': 'Performance Evaluation', 'verbose_name_plural': 'Performance Evaluations'},
        ),
        migrations.AlterField(
            model_name='performanceevaluation',
            name='attendance',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performanceevaluation',
            name='attitude',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performanceevaluation',
            name='communication_skills',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performanceevaluation',
            name='cooperation',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performanceevaluation',
            name='creativity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performanceevaluation',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_evaluations', to='employee.department'),
        ),
        migrations.AlterField(
            model_name='performanceevaluation',
            name='dependability',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performanceevaluation',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='performanceevaluation',
            name='evaluation_period',
            field=models.CharField(blank=True, default='', help_text='For example: WK:10/Nov/2025 - 16/Nov/2025', max_length=120),
        ),
        migrations.AlterField(
            model_name='performanceevaluation',
            name='job_knowledge',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performanceevaluation',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_performance_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='performanceevaluation',
            name='multitasking',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performanceevaluation',
            name='productivity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performanceevaluation',
            name='professionalism',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performanceevaluation',
            name='punctuality',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performanceevaluation',
            name='team_skills',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performanceevaluation',
            name='technical_skills',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performanceevaluation',
            name='total_score',
            field=models.PositiveIntegerField(default=0, help_text='Sum of all 15 metrics (max 1500)'),
        ),
        migrations.AlterField(
            model_name='performanceevaluation',
            name='work_consistency',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performanceevaluation',
            name='work_quality',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
