# Generated by Django 5.2.7 on 2025-10-24 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('performance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceevaluation',
            name='evaluator',
            field=models.ForeignKey(blank=True, help_text='Admin, Manager, or Client who gave the evaluation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='performanceevaluation',
            index=models.Index(fields=['employee'], name='performance_employe_2c0d9d_idx'),
        ),
        migrations.AddIndex(
            model_name='performanceevaluation',
            index=models.Index(fields=['department'], name='performance_departm_62f47e_idx'),
        ),
        migrations.AddIndex(
            model_name='performanceevaluation',
            index=models.Index(fields=['week_number', 'year'], name='performance_week_nu_ec6166_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='performanceevaluation',
            unique_together={('employee', 'week_number', 'year', 'evaluation_type')},
        ),
    ]
