# Generated by Django 5.2.7 on 2025-10-14 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('performance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceevaluation',
            name='evaluator',
            field=models.ForeignKey(blank=True, help_text='The Admin/Manager/Client who gave the evaluation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='performanceevaluation',
            unique_together={('employee', 'week_number', 'year', 'evaluation_type')},
        ),
    ]
