# Generated by Django 5.2.7 on 2025-11-02 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_initial'),
        ('performance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceevaluation',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this evaluation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='performanceevaluation',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department under which the evaluation is recorded.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_performances', to='employee.department'),
        ),
        migrations.AddField(
            model_name='performanceevaluation',
            name='employee',
            field=models.ForeignKey(help_text='Employee whose performance is being evaluated.', on_delete=django.db.models.deletion.CASCADE, related_name='performance_evaluations', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='performanceevaluation',
            name='evaluator',
            field=models.ForeignKey(blank=True, help_text='Person who conducted the evaluation (Admin/Manager/Client).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='performanceevaluation',
            index=models.Index(fields=['employee', 'week_number', 'year'], name='performance_employe_71064c_idx'),
        ),
        migrations.AddIndex(
            model_name='performanceevaluation',
            index=models.Index(fields=['department', 'week_number', 'year'], name='performance_departm_fb675f_idx'),
        ),
        migrations.AddIndex(
            model_name='performanceevaluation',
            index=models.Index(fields=['evaluation_type', 'average_score'], name='performance_evaluat_e49851_idx'),
        ),
        migrations.AddIndex(
            model_name='performanceevaluation',
            index=models.Index(fields=['-average_score'], name='performance_average_0d1686_idx'),
        ),
        migrations.AddIndex(
            model_name='performanceevaluation',
            index=models.Index(fields=['review_date'], name='performance_review__14e415_idx'),
        ),
        migrations.AddIndex(
            model_name='performanceevaluation',
            index=models.Index(fields=['is_finalized'], name='performance_is_fina_5a4ded_idx'),
        ),
        migrations.AddConstraint(
            model_name='performanceevaluation',
            constraint=models.UniqueConstraint(fields=('employee', 'week_number', 'year', 'evaluation_type'), name='unique_employee_week_eval_type'),
        ),
        migrations.AddConstraint(
            model_name='performanceevaluation',
            constraint=models.CheckConstraint(condition=models.Q(('week_number__gte', 1), ('week_number__lte', 53)), name='valid_week_number'),
        ),
        migrations.AddConstraint(
            model_name='performanceevaluation',
            constraint=models.CheckConstraint(condition=models.Q(('average_score__gte', 0), ('average_score__lte', 100)), name='valid_average_score'),
        ),
    ]
