# Generated by Django 5.2.7 on 2025-10-26 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_department_code_alter_employee_contact_number_and_more'),
        ('performance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceevaluation',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department under which the evaluation is recorded.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_performances', to='employee.department'),
        ),
        migrations.AlterField(
            model_name='performanceevaluation',
            name='employee',
            field=models.ForeignKey(help_text='Employee whose performance is being evaluated.', on_delete=django.db.models.deletion.CASCADE, related_name='performance_evaluations', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='performanceevaluation',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Ranking within department/week.', null=True),
        ),
        migrations.AlterField(
            model_name='performanceevaluation',
            name='total_score',
            field=models.PositiveIntegerField(default=0, help_text='Sum of all metrics (max 1500).'),
        ),
    ]
