# Generated by Django 5.2.7 on 2025-10-22 10:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceevaluation',
            name='review_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
