# Generated by Django 5.2.7 on 2025-10-27 06:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_status'),
        ('performance', '0003_alter_performanceevaluation_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='performanceevaluation',
            index=models.Index(fields=['evaluation_type'], name='performance_evaluat_5fdec2_idx'),
        ),
        migrations.AddIndex(
            model_name='performanceevaluation',
            index=models.Index(fields=['average_score'], name='performance_average_93415c_idx'),
        ),
    ]
