# Generated by Django 5.2.7 on 2025-10-23 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('weekly', 'Weekly Report'), ('monthly', 'Monthly Report'), ('manager', 'Manager-wise Report'), ('department', 'Department-wise Report')], max_length=20)),
                ('year', models.PositiveSmallIntegerField(help_text='Report year')),
                ('week_number', models.PositiveSmallIntegerField(blank=True, help_text='Week number (for weekly/manager/department reports)', null=True)),
                ('month', models.PositiveSmallIntegerField(blank=True, help_text='Month number (for monthly reports)', null=True)),
                ('payload', models.JSONField(help_text='Cached JSON data (aggregated summary and metrics)')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.FileField(blank=True, help_text='Optional stored PDF/Excel file path', null=True, upload_to='reports/')),
                ('is_active', models.BooleanField(default=True, help_text='Mark report as active or archived')),
                ('department', models.ForeignKey(blank=True, help_text='Department for department-wise reports', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_reports', to='employee.department')),
            ],
            options={
                'verbose_name': 'Cached Report',
                'verbose_name_plural': 'Cached Reports',
                'ordering': ['-generated_at'],
            },
        ),
    ]
