# Generated by Django 5.2.7 on 2025-11-02 06:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('weekly', 'Weekly Performance Report'), ('monthly', 'Monthly Performance Report'), ('quarterly', 'Quarterly Performance Report'), ('annual', 'Annual Performance Report'), ('manager', 'Manager Team Report'), ('department', 'Department Analytics Report'), ('employee', 'Individual Employee Report'), ('custom', 'Custom Period Report')], db_index=True, help_text='Type of report being cached.', max_length=20)),
                ('year', models.PositiveSmallIntegerField(help_text='Report year (e.g., 2025).', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('week_number', models.PositiveSmallIntegerField(blank=True, help_text='ISO week number (1-53) for weekly reports.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(53)])),
                ('month', models.PositiveSmallIntegerField(blank=True, help_text='Month number (1-12) for monthly reports.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('quarter', models.PositiveSmallIntegerField(blank=True, help_text='Quarter number (1-4) for quarterly reports.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('start_date', models.DateField(blank=True, help_text='Start date for custom period reports.', null=True)),
                ('end_date', models.DateField(blank=True, help_text='End date for custom period reports.', null=True)),
                ('payload', models.JSONField(default=dict, help_text='Cached JSON data (aggregated metrics, KPIs, summaries).')),
                ('report_name', models.CharField(blank=True, help_text='Human-readable report name (auto-generated).', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description or notes about the report.')),
                ('report_hash', models.CharField(blank=True, help_text='SHA-256 hash of payload for change detection.', max_length=64)),
                ('file_path', models.FileField(blank=True, help_text='Generated PDF/Excel file path.', null=True, upload_to=reports.models.report_upload_path)),
                ('file_size', models.PositiveBigIntegerField(blank=True, help_text='File size in bytes.', null=True)),
                ('file_format', models.CharField(blank=True, choices=[('pdf', 'PDF'), ('xlsx', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], help_text='Export file format.', max_length=10)),
                ('generated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the report was generated.')),
                ('version', models.PositiveSmallIntegerField(default=1, help_text='Report version number (increments on regeneration).')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this report is currently active.')),
                ('is_archived', models.BooleanField(db_index=True, default=False, help_text='Indicates if this report has been archived (older data).')),
                ('access_count', models.PositiveIntegerField(default=0, help_text='Number of times report has been accessed.')),
                ('last_accessed_at', models.DateTimeField(blank=True, help_text='Last time report was accessed.', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for temporary reports.', null=True)),
                ('record_count', models.PositiveIntegerField(default=0, help_text='Number of records in the report.')),
                ('average_score', models.DecimalField(blank=True, decimal_places=2, help_text='Average performance score in report.', max_digits=5, null=True)),
                ('department', models.ForeignKey(blank=True, help_text='Department for department-wise reports.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_reports', to='employee.department')),
                ('employee', models.ForeignKey(blank=True, help_text='Employee for individual reports.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_reports', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Cached Report',
                'verbose_name_plural': 'Cached Reports',
                'ordering': ['-generated_at', '-version'],
            },
        ),
    ]
