# Generated by Django 5.2.7 on 2025-11-02 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedreport',
            name='generated_by',
            field=models.ForeignKey(blank=True, help_text='User who generated this report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cachedreport',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Manager for manager-wise reports.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cachedreport',
            index=models.Index(fields=['report_type', 'year'], name='reports_cac_report__563ad4_idx'),
        ),
        migrations.AddIndex(
            model_name='cachedreport',
            index=models.Index(fields=['year', 'month'], name='reports_cac_year_983a2f_idx'),
        ),
        migrations.AddIndex(
            model_name='cachedreport',
            index=models.Index(fields=['year', 'week_number'], name='reports_cac_year_953e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='cachedreport',
            index=models.Index(fields=['generated_at'], name='reports_cac_generat_7e0aef_idx'),
        ),
        migrations.AddIndex(
            model_name='cachedreport',
            index=models.Index(fields=['is_active', 'generated_at'], name='reports_cac_is_acti_b19ed9_idx'),
        ),
        migrations.AddIndex(
            model_name='cachedreport',
            index=models.Index(fields=['manager', 'year'], name='reports_cac_manager_8a7ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='cachedreport',
            index=models.Index(fields=['department', 'year'], name='reports_cac_departm_e398ad_idx'),
        ),
        migrations.AddIndex(
            model_name='cachedreport',
            index=models.Index(fields=['-access_count'], name='reports_cac_access__4368e4_idx'),
        ),
        migrations.AddConstraint(
            model_name='cachedreport',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('report_type', 'year', 'week_number', 'month', 'quarter', 'manager', 'department', 'employee'), name='unique_report_per_period_entity'),
        ),
    ]
