# Generated by Django 5.2.7 on 2025-10-26 18:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_department_code_alter_employee_contact_number_and_more'),
        ('reports', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedreport',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department reference for department-wise reports', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_reports', to='employee.department'),
        ),
        migrations.AlterField(
            model_name='cachedreport',
            name='file_path',
            field=models.FileField(blank=True, help_text='Optional path to generated PDF or Excel file', null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='cachedreport',
            name='generated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cachedreport',
            name='generated_by',
            field=models.ForeignKey(blank=True, help_text='User or system who generated this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cached_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cachedreport',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Active or archived flag'),
        ),
        migrations.AlterField(
            model_name='cachedreport',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Manager reference for manager-wise reports', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cachedreport',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Month number (used for monthly reports)', null=True),
        ),
        migrations.AlterField(
            model_name='cachedreport',
            name='report_type',
            field=models.CharField(choices=[('weekly', 'Weekly Report'), ('monthly', 'Monthly Report'), ('manager', 'Manager-wise Report'), ('department', 'Department-wise Report')], help_text='Type of report (weekly, monthly, manager, department)', max_length=20),
        ),
        migrations.AlterField(
            model_name='cachedreport',
            name='week_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Week number (used for weekly/manager/department reports)', null=True),
        ),
    ]
