# Generated by Django 5.2.7 on 2025-10-23 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_role_alter_employee_contact_number_and_more'),
        ('reports', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cachedreport',
            name='unique_cached_report_per_period',
        ),
        migrations.AddField(
            model_name='cachedreport',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department for department-wise reports', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_reports', to='employee.department'),
        ),
        migrations.AddField(
            model_name='cachedreport',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Manager for manager-wise reports', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cachedreport',
            name='file_path',
            field=models.FileField(blank=True, help_text='Optional stored PDF/Excel file path', null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='cachedreport',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Month number (for monthly reports)', null=True),
        ),
        migrations.AlterField(
            model_name='cachedreport',
            name='payload',
            field=models.JSONField(help_text='Cached JSON data (aggregated summary and metrics)'),
        ),
        migrations.AlterField(
            model_name='cachedreport',
            name='report_type',
            field=models.CharField(choices=[('weekly', 'Weekly Report'), ('monthly', 'Monthly Report'), ('manager', 'Manager-wise Report'), ('department', 'Department-wise Report')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cachedreport',
            name='week_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Week number (for weekly/manager/department reports)', null=True),
        ),
        migrations.AlterField(
            model_name='cachedreport',
            name='year',
            field=models.PositiveSmallIntegerField(help_text='Report year'),
        ),
        migrations.AddIndex(
            model_name='cachedreport',
            index=models.Index(fields=['report_type'], name='reports_cac_report__d5447b_idx'),
        ),
        migrations.AddConstraint(
            model_name='cachedreport',
            constraint=models.UniqueConstraint(fields=('report_type', 'year', 'week_number', 'month', 'manager', 'department'), name='unique_cached_report_per_period'),
        ),
    ]
