# Generated by Django 5.2.7 on 2025-10-24 07:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedreport',
            name='file_path',
            field=models.FileField(blank=True, help_text='Optional stored PDF or Excel file path', null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='cachedreport',
            name='generated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when report was generated'),
        ),
        migrations.AlterField(
            model_name='cachedreport',
            name='payload',
            field=models.JSONField(help_text='Cached JSON data (aggregated summary, KPIs, and metrics)'),
        ),
        migrations.AlterField(
            model_name='cachedreport',
            name='report_type',
            field=models.CharField(choices=[('weekly', 'Weekly Report'), ('monthly', 'Monthly Report'), ('manager', 'Manager-wise Report'), ('department', 'Department-wise Report')], help_text='Type of report (weekly, monthly, etc.)', max_length=20),
        ),
        migrations.AlterField(
            model_name='cachedreport',
            name='week_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Week number (for weekly, manager, department reports)', null=True),
        ),
        migrations.AlterField(
            model_name='cachedreport',
            name='year',
            field=models.PositiveSmallIntegerField(help_text='Report year (e.g., 2025)'),
        ),
    ]
