# Generated by Django 5.2.7 on 2025-10-27 06:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_status'),
        ('reports', '0003_alter_cachedreport_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cachedreport',
            index=models.Index(fields=['report_type', 'year', 'week_number'], name='reports_cac_report__a25b66_idx'),
        ),
        migrations.AddIndex(
            model_name='cachedreport',
            index=models.Index(fields=['report_type', 'year', 'month'], name='reports_cac_report__c75975_idx'),
        ),
    ]
