# Generated by Django 5.2.7 on 2025-10-28 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_cachedreport_reports_cac_report__a25b66_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cachedreport',
            name='reports_cac_report__a25b66_idx',
        ),
        migrations.RemoveIndex(
            model_name='cachedreport',
            name='reports_cac_report__c75975_idx',
        ),
        migrations.AddField(
            model_name='cachedreport',
            name='report_name',
            field=models.CharField(blank=True, help_text='Readable report name (auto-generated for dashboard display).', max_length=255),
        ),
        migrations.AlterField(
            model_name='cachedreport',
            name='file_path',
            field=models.FileField(blank=True, help_text='Path to generated PDF/Excel file (if available).', null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='cachedreport',
            name='generated_by',
            field=models.ForeignKey(blank=True, help_text='User or system that generated this report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cached_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cachedreport',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Active or archived flag.'),
        ),
        migrations.AlterField(
            model_name='cachedreport',
            name='payload',
            field=models.JSONField(help_text='Cached JSON data (aggregated summary, KPIs, and metrics).'),
        ),
    ]
