# Generated by Django 5.2.7 on 2025-11-02 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(help_text='Short notification message or description.', max_length=255)),
                ('link', models.CharField(blank=True, help_text='Optional URL or route link for redirection (e.g., /reports/weekly/?week=44&year=2025)', max_length=500, null=True)),
                ('category', models.CharField(choices=[('performance', 'Performance'), ('feedback', 'Feedback'), ('system', 'System'), ('attendance', 'Attendance'), ('leave', 'Leave'), ('announcement', 'Announcement')], db_index=True, default='performance', help_text='Category of the notification', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='medium', help_text='Priority level of the notification', max_length=10)),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Indicates whether the notification has been read.')),
                ('read_at', models.DateTimeField(blank=True, help_text='Timestamp when the notification was marked as read.', null=True)),
                ('auto_delete', models.BooleanField(default=True, help_text='If True → delete automatically after being read. If False → keep record marked as read.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the notification was created.')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Optional expiration timestamp. Notification auto-expires after this time.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional structured data for the notification (action_id, reference_id, etc.)')),
                ('department', models.ForeignKey(blank=True, help_text='Optional: department-wide notification scope.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='employee.department')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
