# Generated by Django 5.2.7 on 2025-10-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(help_text='Notification message text.', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('auto_delete', models.BooleanField(default=True, help_text='If True → delete after read; False → keep record as read.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
