# Generated by Django 5.2.7 on 2025-10-24 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(help_text='Short notification message or description.', max_length=255)),
                ('is_read', models.BooleanField(default=False, help_text='Indicates if the notification has been read.')),
                ('read_at', models.DateTimeField(blank=True, help_text='Timestamp when the notification was read.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this notification was created.')),
                ('auto_delete', models.BooleanField(default=True, help_text='If True → delete automatically after being read. If False → keep record marked as read.')),
                ('department', models.ForeignKey(blank=True, help_text='Optional: department-wide notification scope.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='employee.department')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
