# Generated by Django 5.2.7 on 2025-10-24 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_initial'),
        ('notifications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AddField(
            model_name='notification',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Optional: department-wide notification scope.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='employee.department'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='auto_delete',
            field=models.BooleanField(default=True, help_text='If True → delete automatically after being read. If False → keep record marked as read.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this notification was created.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='employee',
            field=models.ForeignKey(help_text='User who will receive this notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Indicates if the notification has been read.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(help_text='Short notification message or description.', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the notification was read.', null=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'),
        ),
    ]
