# Generated by Django 5.2.7 on 2025-10-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(default='performance', help_text='Category of the notification (performance, feedback, system, etc.)', max_length=50),
        ),
    ]
