# Generated by Django 5.2.7 on 2025-10-31 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, help_text='Optional URL or route link for redirection (e.g., /reports/weekly/?week=44&year=2025)', max_length=255, null=True),
        ),
    ]
